import re
import sys

def main():
    """
    Strips unused glyphs from an EpdFont C++ header file, keeping only standard ASCII 0x20-0x7E.
    
    Usage:
        python scripts/strip_heading_font.py <font_name>
    
    Example:
        python scripts/strip_heading_font.py syne_bold_10
        
    The script reads `lib/EpdFont/src/builtinFonts/<font_name>.h`, parses its
    bitmaps, glyphs, and intervals, keeps only codepoints in the range 0x20-0x7E,
    and writes the optimized font to `<font_name>_stripped.h`.
    
    You can then manually rename the stripped file to replace the original.
    """
    if len(sys.argv) < 2:
        print("Usage: strip_heading_font.py <font_name>")
        sys.exit(1)
        
    font_name = sys.argv[1]
    path = f'lib/EpdFont/src/builtinFonts/{font_name}.h'
    out_path = f'lib/EpdFont/src/builtinFonts/{font_name}_stripped.h'
    
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    
    # Remove all single-line comments before regex parsing
    text = re.sub(r'//.*', '', text)

    bitmaps_match = re.search(r'static const uint8_t PROGMEM ' + font_name + r'Bitmaps\[\d+\] = \{(.*?)\};', text, re.DOTALL)
    bitmaps_str = bitmaps_match.group(1).replace('\n', ' ')
    bitmaps = [int(x.strip(), 16) for x in bitmaps_str.split(',') if x.strip()]

    glyphs_match = re.search(r'static const EpdGlyph PROGMEM ' + font_name + r'Glyphs\[\] = \{(.*?)\};', text, re.DOTALL)
    glyph_lines = [x.strip() for x in glyphs_match.group(1).split('}') if '{' in x]

    intervals_match = re.search(r'static const EpdUnicodeInterval PROGMEM ' + font_name + r'Intervals\[\] = \{(.*?)\};', text, re.DOTALL)
    interval_lines = [x.strip() for x in intervals_match.group(1).split('}') if '{' in x]

    intervals = []
    for line in interval_lines:
        parts = [x for x in line.replace('{', '').split(',') if x.strip()]
        vals = [int(x.strip(), 16) for x in parts[:3]]
        intervals.append(vals)

    glyphs = []
    for line in glyph_lines:
        vals = [int(x.strip(), 10) if not x.strip().startswith('0x') else int(x.strip(), 16) for x in line.replace('{', '').split(',') if x.strip()]
        glyphs.append(vals)

    # find bottom metadata (advance_y, ascender, descender, is_2bit, etc.)
    meta_match = re.search(r'static const EpdFontData ' + font_name + r' = \{(.*?)\};', text, re.DOTALL)
    meta = [x.strip() for x in meta_match.group(1).split(',') if x.strip()]
    
    new_bitmaps = []
    new_glyphs = []
    kept_cps = []
    
    current_offset = 0
    glyph_idx = 0
    
    for start, end, offset in intervals:
        for cp in range(start, end + 1):
            if 0x20 <= cp <= 0x7E:
                # Keep this character
                g = glyphs[glyph_idx]
                w, h, ax, l, t, dlen, doff = g
                
                # Copy bitmap
                b_slice = bitmaps[doff:doff+dlen]
                new_bitmaps.extend(b_slice)
                
                new_glyphs.append([w, h, ax, l, t, dlen, current_offset])
                current_offset += dlen
                kept_cps.append(cp)
            glyph_idx += 1
            
    # Build new contiguous intervals based on kept codepoints
    new_intervals = []
    if kept_cps:
        start_cp = kept_cps[0]
        last_cp = kept_cps[0]
        start_idx = 0
        
        for i in range(1, len(kept_cps)):
            cp = kept_cps[i]
            if cp == last_cp + 1:
                last_cp = cp
            else:
                new_intervals.append([start_cp, last_cp, start_idx])
                start_cp = cp
                last_cp = cp
                start_idx = i
        new_intervals.append([start_cp, last_cp, start_idx])

    # Write output file
    with open(out_path, 'w') as f:
        f.write(f'/**\n * generated by fontconvert.py (stripped)\n * name: {font_name}\n * mode: 1-bit\n */\n')
        f.write('#pragma once\n#include "EpdFontData.h"\n\n')
        
        f.write(f'static const uint8_t PROGMEM {font_name}Bitmaps[{len(new_bitmaps)}] = {{\n    ')
        for i, b in enumerate(new_bitmaps):
            f.write(f'0x{b:02X}, ')
            if (i + 1) % 16 == 0:
                f.write('\n    ')
        f.write('\n};\n\n')
        
        f.write(f'static const EpdGlyph PROGMEM {font_name}Glyphs[] = {{\n')
        for g in new_glyphs:
            f.write(f'    {{ {g[0]}, {g[1]}, {g[2]}, {g[3]}, {g[4]}, {g[5]}, {g[6]} }},\n')
        f.write('};\n\n')
        
        f.write(f'static const EpdUnicodeInterval PROGMEM {font_name}Intervals[] = {{\n')
        for iv in new_intervals:
            f.write(f'    {{ 0x{iv[0]:04X}, 0x{iv[1]:04X}, 0x{iv[2]:X} }},\n')
        f.write('};\n\n')
        
        f.write(f'static const EpdFontData {font_name} = {{\n')
        f.write(f'    {font_name}Bitmaps,\n')
        f.write(f'    {font_name}Glyphs,\n')
        f.write(f'    {font_name}Intervals,\n')
        f.write(f'    {len(new_intervals)},\n')
        f.write(f'    {meta[4]},\n') # advance_y
        f.write(f'    {meta[5]},\n') # ascender
        f.write(f'    {meta[6]},\n') # descender
        f.write(f'    {meta[7]},\n') # is_2bit
        f.write('};\n')

    print(f"Stripped font saved to {out_path}")
    print(f"Original bitmaps length: {len(bitmaps)}")
    print(f"New bitmaps length: {len(new_bitmaps)}")
    print(f"Original glyphs length: {len(glyphs)}")
    print(f"New glyphs length: {len(new_glyphs)}")
    print(f"Original intervals length: {len(intervals)}")
    print(f"New intervals length: {len(new_intervals)}")

if __name__ == '__main__':
    main()
